name: owner
label: Organization Owner
description: Full ownership of the organization
policies: []
permissions:
  organization: 
    actions: [read, update, delete]
    filters:
      - ['id', '=', '$user.spaceId']
  user:
    actions: [read]
  member:
    actions: [create, read, update, delete]
  invitation:
    actions: [read, create, delete]
  team:
    actions: [create, read, update, delete]
